amcl:
  ros__parameters:

    # particle filter guesses for amcl - value selected based on cpu storage
    min_particles: 1000
    max_particles: 5000

    # update thresholds - basically how often amcl updates (currently set to every 5cm)
    update_min_d: 0.05
    update_min_a: 0.05

    # lidar settings
    laser_min_range: 0.15  # min max distance for ignoring scan
    laser_max_range: 16.0
    max_beams: 60 # subsample beam count
    laser_model_type: 'likelihood_field_prob'

  # .... possible alternatives ............................................

      # likelihood_field - standard fast and baseline model
      # likelihood_field_prob - handles noise better
      # beam - most physically accurate model but too slow for mirtes cpu
      # gompertz - not well documented
  # ........................................................................

    # z - weights (changes based on the model choosen)
    z_hit: 0.8 # (how much % of the scan readings should match real obstacles in the map) --> took 80%
    z_rand: 0.2 # (how much % of the scan readings to consider as random noise)
    sigma_hit: 0.1 # how much beam error to allow

    # quality
    # the values are chosen such that amcl remembers long-term localization quality very slowly, but reacts quickly to recent bad scans.
    # this was done to detect sudden localisation failures
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1

    # coordinate frames
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    transform_tolerance: 3.0

    # initial cords
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0

    # lidar scan publishing
    scan_topic: /scan
