rtabmap:
  ros__parameters:

    # frames
    frame_id: base_link
    odom_frame_id: odom
    map_frame_id: map

    # topics
    subscribe_depth: true # depth camera data
    subscribe_scan: true  # lidar scan deets

    # sensor topics
    depth_topic: /camera/depth/image_raw
    rgb_topic: /camera/color/image_raw
    camera_info_topic: /camera/color/camera_info
    # gives deets on focal length, optical center, image distortion model, camera matrix
    scan_topic: /scan

    # sync settings
    approx_sync: true               # approximate timestamp synchronization (Hz)
    queue_size: 10                  # no. of recent messages while trying to find matching timestamps (Hz) --> basically to keep
                                    # synchronization in check

    # mapping settings
    Mem/IncrementalMemory: "true"   # true --> mapping mode & false --> localisation mode
    Mem/InitWMWithAllNodes: "false" # controls whether all existing map nodes are loaded into working memory at startup

    # loop closure
    Rtabmap/DetectionRate: "1"      # [Hz] --> freq updates
    Rtabmap/TimeThr: "0"            # no time limit for processing

    # visual features
    Vis/MinInliers: "10"            # min. no. of good visual feature matches needed to accept a visual transformation
    Vis/InlierDistance: "0.1"       # [cm]  acceptable dist bw 2 matched features s.t they can be counted as good matches

    # optimisation
    Optimizer/Strategy: "1"         # gto basically the type of graph optimizer that corrects for pose conflicts bw odom and loop closure
    Optimizer/Iterations: "20"      # controls how hard the optimizer works each time to fix the map

    # CPU optimisation for Mirte ARM
    RGBD/NeighborLinkRefining: "false"
    RGBD/ProximityBySpace: "false"
    Grid/FromDepth: "true"          # creates the occupancy grid
    Grid/RangeMax: "4.0"            # set to match the depth cam constraints -->  uses only depth/grid points upto 4 m away.






    # the RGBD stuff is a lil confusing but from what i understand
    #Parameter                     | Value   | Function
    ## -------------------------------------------------------------------------
    ## RGBD/NeighborLinkRefining     | false   | Disables extra RGB-D refinement between consecutive/neighboring poses.
    ##                               |         | Saves CPU, but relies more on odometry for short-term movement accuracy.
    ##
    ## RGBD/ProximityBySpace         | false   | Disables searching nearby old poses for extra RGB-D constraints.
    ##                               |         | Saves CPU, but may reduce loop/proximity correction opportunities.
